---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (SLES_SAP)
    tags: always
    zypper:
      name: '*'
      state: latest
    changed_when: false
    when: ansible_distribution == 'SLES_SAP' 

- hosts: all
  become: true
  tasks: 
  
  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG67bO+uHpnETOFqyGAsOOTrRSnq4n0yWKTzQD+IuIKF ansible"

- hosts: workstations
  become: true
  tasks:
  
  - name: install unzip
    zypper:
      name: unzip
      state: latest

  - name: install terraform
    unarchive: 
      src: https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: db_server
  become: true
  tasks:

  - name: install apache2 and php packages using zypper module
    tags: apache2, SLES, httpd
    zypper:
      name: 
        - httpd
        - apache2-mod_php74
      state: present
    when: ansible_distribution == 'SLES_SAP'

#  - name: Start Apache web server using shell module
#    tags: apache, start, service, SLES
#    shell:
#       " systemctl start apache2.service"
#    register: lsout
    #when: ansible_os_family == 'Suse'
#    when: ansible_distribution == 'SLES_SAP'
  - name: Start Apache web server on SLES_SAP
    tags: apache, start, service, SLES
    service:
      name: apache2.service
      state: started
      enabled: yes
    when: ansible_distribution == 'SLES_SAP'

# This playbook works if th variable reg has change. 
# Therefore a change in the service is require, example can be
# changing the ServerAdmin email.
#  - name: restart apache2 service
#    tags: apache, restart, service
#    service:
#      name: apache2.service
#      state: restarted
#    when: reg.changed

  - name: Check if directory /srv/www/htdocs/ exist in remote server
    tags: check, dir
    stat:
      path: /srv/www/htdocs/
    register: dir_exist

  - name: "echo if directory already existed"
    tags: echo, debug
    debug:
      msg: "the /srv/www/htdocs/ directory already existed"
    when: dir_exist.stat.exists

  - name: Create directory in remote server
    tags: create, dir
    file:
      path: /srv/www/htdocs/
      state: directory
      mode: 0755
      group: root
      owner: admin
    when: dir_exist.stat.exists == false

  - name: copy default html file for site
    tags: apache, start, service, SLES
    copy:
      src: default_site.html
      dest: /srv/www/htdocs/index.html
      owner: admin
      group: root
      mode: 0644

