---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (SLES_SAP)
    tags: always
    zypper:
      name: '*'
      state: latest
    when: ansible_distribution == 'SLES_SAP' 

- hosts: db_server
  become: true
  tasks:

  - name: install apache2 and php packages using zypper module
    tags: apache2, SLES, httpd
    zypper:
      name: 
        - httpd
        - apache2-mod_php74
      state: present
    when: ansible_distribution == 'SLES_SAP'

  - name: Start Apache web server using shell module
    tags: apache, start, service, SLES
    shell:
       " systemctl start apache2.service"
    register: lsout
    #when: ansible_os_family == 'Suse'
    when: ansible_distribution == 'SLES_SAP'

  - name: Check if directory /srv/www/htdocs/ exist in remote server
    tags: check, dir
    stat:
      path: /srv/www/htdocs/
    register: dir_exist

  - name: "echo if directory already existed"
    tags: echo, debug
    debug:
      msg: "the /srv/www/htdocs/ directory already existed"
    when: dir_exist.stat.exists

  - name: Create directory in remote server
    tags: create, dir
    file:
      path: /srv/www/htdocs/
      state: directory
      mode: 0755
      group: root
      owner: admin
    when: dir_exist.stat.exists == false

  - name: copy default html file for site
    tags: apache, start, service, SLES
    copy:
      src: default_site.html
      dest: /srv/www/htdocs/index.html
      owner: admin
      group: root
      mode: 0644

