---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (SLES_SAP)
    tags: always
    zypper:
      name: '*'
      state: latest
    changed_when: false
    when: ansible_distribution == 'SLES_SAP' 

- hosts: all
  become: true
  roles:
    - base
  
- hosts: workstations
  become: true
  roles:
    - workstations

- hosts: db_server
  become: true
  roles:
    - db_server
